# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Fetch Iris for Sodium
      uses: actions/checkout@v2
      with:
        repository: 'IrisShaders/Iris'
        ref: '1.17'
        path: 'iris'
    - name: Iris publishToMavenLocal
      run: cd ./iris && ./gradlew publishToMavenLocal && cd ..
    - name: Fetch Sodium
      uses: actions/checkout@v2
      with:
        repository: 'razboy20/sodium-fabric'
        ref: '1.17.x/iris'
        path: 'sodium-fabric'
    - name: Sodium publishToMavenLocal
      run: cd ./sodium-fabric && ./gradlew publishToMavenLocal && cd ..
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bundleSodium --stacktrace
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: build/libs
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        prerelease: true
        files: build/libs
